### ISSUE TITLE
Impossible to build with ESP32 1.0.1 and AsyncTCP 1.0.3

### ISSUE THREAD

**Issue by christophepersoz** [me-no-dev/AsyncTCP#42]
Hello,

I'm currently facing to this issue when trying to bulked a simple WebSocket example on my ESP WEMOS LOLIN 32.

I had a look on several issues reported, all of them said to compile AsyncTCP 1.0.3 with ESP32 1.0.1, but is seems that there is a another problem though.
Any idea to make it works?

```
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCP.cpp: In member function 'bool AsyncClient::connect(IPAddress, uint16_t)':
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCP.cpp:115:8: error: 'ip_addr_t {aka struct ip_addr}' has no member named 'addr'
   addr.addr = ip;
        ^
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCP.cpp: In member function 'bool AsyncClient::connect(const char*, uint16_t)':
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCP.cpp:148:35: error: 'ip_addr_t {aka struct ip_addr}' has no member named 'addr'
     return connect(IPAddress(addr.addr), port);
                                   ^
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCP.cpp: In member function 'bool AsyncClient::operator==(const AsyncClient&)':
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCP.cpp:192:66: error: 'ip_addr_t {aka struct ip_addr}' has no member named 'addr'
   return (_pcb != NULL && other._pcb != NULL && (_pcb->remote_ip.addr == other._pcb->remote_ip.addr) && (_pcb->remote_port == other._pcb->remote_port));
                                                                  ^
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCP.cpp:192:96: error: 'ip_addr_t {aka struct ip_addr}' has no member named 'addr'
   return (_pcb != NULL && other._pcb != NULL && (_pcb->remote_ip.addr == other._pcb->remote_ip.addr) && (_pcb->remote_port == other._pcb->remote_port));
                                                                                                ^
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCPbuffer.cpp: In constructor 'AsyncTCPbuffer::AsyncTCPbuffer(AsyncClient*)':
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCPbuffer.cpp:35:15: error: 'panic' was not declared in this scope
         panic();

               ^
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCP.cpp: In member function 'void AsyncClient::_dns_found(const ip_addr*)':
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCP.cpp:473:31: error: 'const struct ip_addr' has no member named 'addr'
     connect(IPAddress(ipaddr->addr), _connect_port);
                               ^
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCP.cpp: In member function 'uint32_t AsyncClient::getRemoteAddress()':
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCP.cpp:586:26: error: 'ip_addr_t {aka struct ip_addr}' has no member named 'addr'
   return _pcb->remote_ip.addr;
                          ^
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCP.cpp: In member function 'uint32_t AsyncClient::getLocalAddress()':
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCP.cpp:598:25: error: 'ip_addr_t {aka struct ip_addr}' has no member named 'addr'
   return _pcb->local_ip.addr;
                         ^
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCPbuffer.cpp: In member function 'virtual size_t AsyncTCPbuffer::write(const uint8_t*, size_t)':
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCPbuffer.cpp:128:23: error: 'panic' was not declared in this scope
                 panic();

                       ^
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCP.cpp: In member function 'void AsyncServer::begin()':
/Users/cp/Developer/_Arduino/libraries/ESPAsyncTCP/src/ESPAsyncTCP.cpp:873:14: error: 'ip_addr_t {aka struct ip_addr}' has no member named 'addr'
   local_addr.addr = (uint32_t) _addr;
              ^
Multiple libraries were found for "WiFi.h"
 Used: /Users/cp/Library/Arduino15/packages/esp32/hardware/esp32/1.0.1/libraries/WiFi
 Not used: /Applications/Arduino.app/Contents/Java/libraries/WiFi
```

Thanks

**Comment by christophepersoz** [comment]
Wrong call. Should call AsyncTCP.h (ESP32) instead of ESPAsyncTCP.h (ESP8266)... Sorry. Closed.
